CREATE TABLE Accounts (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	Email NVARCHAR(320) NOT NULL UNIQUE,
	[Password] NVARCHAR(16) NOT NULL,
	CreatedAt SMALLDATETIME NOT NULL
);

CREATE TABLE Videos (
	Id INT IDENTITY(1, 1) PRIMARY KEY,
	Title NVARCHAR(200) NOT NULL UNIQUE,
	Link NVARCHAR(2000) NOT NULL UNIQUE,
	[Language] NVARCHAR(30) NOT NULL,
	AddedAt SMALLDATETIME NOT NULL
);

CREATE TABLE AccountsVideos (
	AccountId INT FOREIGN KEY REFERENCES Accounts(Id) NOT NULL,
	VideoId INT FOREIGN KEY REFERENCES Videos(Id) NOT NULL
);

CREATE TABLE Subtitles (
	Id INT IDENTITY(1,1) PRIMARY KEY,
    VideoId INT FOREIGN KEY REFERENCES Videos(Id) NOT NULL,
	Content NVARCHAR(4000) DEFAULT 'No subtitle' NOT NULL,
	[Language] NVARCHAR(30) NOT NULL,
    AddedBy NVARCHAR(101) NOT NULL,
	AddedAt SMALLDATETIME NOT NULL
);

CREATE TABLE Transcriptions (
	Id INT IDENTITY(1,1) PRIMARY KEY,
	VideoId INT FOREIGN KEY REFERENCES Videos(Id) UNIQUE NOT NULL,
	Content NVARCHAR(4000) DEFAULT 'No transcription' NOT NULL,
	AddedBy NVARCHAR(101) NOT NULL,
	AddedAt SMALLDATETIME NOT NULL
);